version: '3'

services:
  starting-elo-microservice:
    build: ./starting-elo-microservice
    volumes:
      - starting-elo-microservice:/usr/src/app
    ports:
      - "5001:5001"
  
  update-elo-microservice:
    build: ./update-elo-microservice
    volumes:
      - update-elo-microservice:/usr/src/app
    ports:
      - "5002:5002"
  
  db-microservice:
    build: ./db-microservice
    volumes:
      - db-microservice:/usr/src/app
    user: root
    depends_on:
      - mysql-db
    ports:
      - "5003:5003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  mysql-db:
    build: ./db-microservice/mysql
    volumes:
      - mysql:/usr/src/app
    ports:
      - "3307:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  chat-server:
    build: ./chat-server
    volumes:
      - chat-server:/usr/src/app
    ports:
      - "5004:5004"

volumes:
  starting-elo-microservice:
  update-elo-microservice:
  db-microservice:
  mysql:
  chat-server:


